apiVersion: kubernetes.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: zonal_cluster
  name: zonal-cluster
spec:
  forProvider:
    description: description
    kmsProvider:
    - keyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: kms_key_resource_name
    labels:
      my_key: my_value
      my_other_key: my_other_value
    master:
    - maintenancePolicy:
      - autoUpgrade: true
        maintenanceWindow:
        - duration: 3h
          startTime: "15:00"
      masterLogging:
      - auditEnabled: true
        clusterAutoscalerEnabled: true
        enabled: true
        eventsEnabled: true
        kubeApiserverEnabled: true
        logGroupIdSelector:
          matchLabels:
            testing.upbound.io/example-name: log_group_resoruce_name
      publicIp: true
      scalePolicy:
      - autoScale:
        - minResourcePresetId: s-c4-m16
      securityGroupIdsRefs:
      - name: security_group_name
      version: "1.30"
      zonal:
      - subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: subnet_resource_name
        zoneSelector:
          matchLabels:
            testing.upbound.io/example-name: subnet_resource_name
    name: name
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_resource_name
    networkPolicyProvider: CALICO
    nodeServiceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: node_service_account_resource_name
    releaseChannel: RAPID
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: service_account_resource_name
    workloadIdentityFederation:
    - enabled: true
