apiVersion: organizationmanager.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: OsLoginSettings
metadata:
  annotations:
    meta.upbound.io/example-id: organizationmanager/v1alpha1/osloginsettings
  labels:
    testing.upbound.io/example-name: my_settings
  name: my-settings
spec:
  forProvider:
    organizationId: sdf4*********3fr
    sshCertificateSettings:
    - enabled: true
    userSshKeySettings:
    - allowManageOwnKeys: true
      enabled: true
