apiVersion: kubernetes.yandex-cloud.upjet.m.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: zonal_cluster_resource_name
  name: zonal-cluster-resource-name
  namespace: upbound-system
spec:
  forProvider:
    description: description
    kmsProvider:
    - keyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: kms_key_resource_name
    labels:
      my_key: my_value
      my_other_key: my_other_value
    master:
    - maintenancePolicy:
      - autoUpgrade: true
        maintenanceWindow:
        - duration: 3h
          startTime: "15:00"
      masterLogging:
      - auditEnabled: true
        clusterAutoscalerEnabled: true
        enabled: true
        eventsEnabled: true
        kubeApiserverEnabled: true
        logGroupId: ${yandex_logging_group.log_group_resoruce_name.id}
      publicIp: true
      securityGroupIdsRefs:
      - name: security_group_name
      version: "1.17"
      zonal:
      - subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: subnet_resource_name
        zone: ru-central1-a
    name: name
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_resource_name
    networkPolicyProvider: CALICO
    nodeServiceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: node_service_account_resource_name
    releaseChannel: RAPID
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: service_account_resource_name
