apiVersion: ydb.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: DatabaseServerless
metadata:
  annotations:
    meta.upbound.io/example-id: ydb/v1alpha1/databaseserverless
  labels:
    testing.upbound.io/example-name: my_ydb
  name: my-ydb
spec:
  forProvider:
    deletionProtection: true
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: yandex_resourcemanager_folder
    name: test-ydb-serverless
